### ISSUE TITLE
Docker-Compose

### ISSUE THREAD

**Issue by Lyrwon** [anchore/harbor-scanner-adapter#21]
Can i user this adapter without using kubernetes or do you have an other adapter-config for docker-compose?

**Comment by zhill** [comment]
Good question! No, kubernetes is not required to use this. The adapter doesn't care how it's deployed as long as Harbor can reach it, and it can reach the Anchore API endpoints and Anchore can pull data from Harbor.

I don't have a docker-compose atm, but it won't be complex for just the adapter. Would you like to deploy the whole stack in compose or just the adapter?

**Comment by Lyrwon** [comment]
I think the best will be, when i deploy the harbor and anchore part in seperate compose-files

**Comment by zhill** [comment]
To make sure I understand, I think you're requesting option 1.

## Option 1:
docker-compose for harbor itself
docker-compose for anchore + adapter

## Option 2:
docker-compose for harbor + adapter
docker-compose for anchore

## Option 3:
docker-compose for harbor
docker-compose for anchore
docker-compose for adapter

**Comment by Lyrwon** [comment]
Yes, option 1 is that what i mean.
At the moment i would run that on the same host

**Comment by CNYuYang** [comment]
> Yes, option 1 is that what i mean.
> At the moment i would run that on the same host

how harbor  adapter  anchore can link each other?

this is my way：

let adapter join harbor`s docker network than harbor can use container name to access adapter

```
//adapter`s compose.yml
network:
  - harbor
```

and adapter use harbor`s virtual network gateway  to  access anchore

```
//adapter`s compose.yml
ANCHORE_ENDPOINT = 172.23.0.1:8443
```

But I don’t want to manually fill in the address of the network gateway. Do you have a better way?
