### ISSUE TITLE
Decouple the CVE description loading and caching from the synchronous request path

### ISSUE THREAD

**Issue by zhill** [anchore/harbor-scanner-adapter#50]
When the adapter gets a request from Harbor to see if the scan is complete, if it finds the image is analyzed it will immediately try to load the vulns and the cve descriptions. If the full descriptions are enabled, this may take a while and can cause the Harbor client to time out while waiting.

The solution for this (assuming no API changes in Anchore) is to decouple the cve description hydration from the request path and have the adapter use an async thread to compose the full response once it sees the image is analyzed.

I think this can be done from a goroutine initiated when the Harbor client asks for the scan result and the adapter finds the image is analyzed. At that point is can fire off the collector job to build the response but return to the caller that the report isn't ready yet. On the next query from the Harbor client, if the response is ready (either in memory or cached on disk), then it can be returned without any subsequent API calls to Anchore.

This would result in a more reliable API call sequence but also support full vuln description loading.

**Comment by bradleyjones** [comment]
Part of the desire for this change is a timeout introduced in the harbor http client used for requests to the scanner (https://github.com/goharbor/harbor/blob/main/src/pkg/scan/rest/v1/client.go#L98). This timeout is now set at 5 seconds so we need to ensure that all requests from our adapter respond within this limit
