### ISSUE TITLE
anchore adapter keep return error "level=error msg="failed executing the scan request" err="failed to add credential got response code 406"

### ISSUE THREAD

**Issue by MaGaoju** [anchore/harbor-scanner-adapter#9]
I have problem with current add credential rules.
in our case method EnsureRegistryCredentials() won't success because during the credential update progress. 
this method will check if credential exist, once exist, it will return 500 as HTTP status code which will directly goes to error :
else if resp.StatusCode != http.StatusOK {
			// More handling
			log.Error("unexpected error response from anchore adding registry credential")
			_return fmt.Errorf("failed to add credential got response code %v", resp.StatusCode)_ 

so we keep have error message                                                                         
time="2019-10-28T08:15:44Z" level=error msg="unexpected error response from anchore adding registry credential"
time="2019-10-28T08:15:44Z" level=error msg="failed executing the scan request" err="failed to add credential got response code 406"
time="2019-10-28T08:15:44Z" level=error msg="returning error response" code=500 message="failed to add credential got response code 406"

![image](https://user-images.githubusercontent.com/13995442/67666093-04af5e80-f9a6-11e9-86ea-0bbaf03da6c5.png)

I have too disable this function to make my system work for now. not sure if this is anchore problem or our anchore enterprise version is using different way to return this error. 
our anchore enterprise API version:  [ base url: / , api version: 0.1.12 ]

**Comment by zhill** [comment]
Is there a proxy between the adapter and Anchore? Anchore should be returning a 500, which is handled in the code. It should be a handled in: https://github.com/anchore/harbor-scanner-adapter/blob/master/pkg/adapter/anchore/adapter.go#L132

**Comment by zhill** [comment]
Looking into this more, the 406 is likely coming as an error from Anchore indicating that it cannot use the provided credential to authenticate to the registry. A verification check is run when the credential is added in the api call and if Anchore cannot confirm that it can login with the credential it will return 406. I will investigate further, but I've not seen this in any of my testing against the master branch of Harbor. What commit (or image digest) of Harbor are you testing with?

**Comment by MaGaoju** [comment]
I saw that part of code, but it didn't goes to update credential condition: below is the full log: I add more debug information to check if Harbor send the correct token, harbor token looks ok for me. but code directly report error in elseif scope... (just highlight the debug log I added.) 
![image](https://user-images.githubusercontent.com/13995442/67731393-fa877180-fa32-11e9-92ad-2176c397e636.png)

**Comment by cafeliker** [comment]
@zhill We were seeing 500 response error when using postman to issue the same request to Anchore; but why it returned 406 with the API call by codes?

Based on the above screenshot of the logs, it said code=500, but the message said response code 406 - really confusing...

ye

**Comment by zhill** [comment]
The log is a little confusing, it's indicating the adapter returns 500 to Harbor when it gets a 406 from the Anchore API. I'm not able to reproduce the error yet. The credentials I'm getting from Harbor via the API are not causing that behavior. I'll add appropriate handlers for the 406 return but in that condition an error response to Harbor is correct since the adapter cannot guarantee that Anchore can access or pull the image for analysis.

**Comment by MaGaoju** [comment]
zhill, I have print out the details:

harbor requesr for debug : resp.statusCode : 406
harbor requesr for debug : http.StatusInternalServerError: 500
harbor requesr for debug : anchoreError.HttpCode: 406
time="2019-10-29T04:36:55Z" level=info msg="I just want to see the detail error 406 message : cannot ping supplied registry with supplied credentials - exception: failed check **to access registry (https://rnd-it,robot$bc42d429-fa05-11e9-b054-1282d7ef7029) - exception: HTTPSConnectionPool(host='rnd-it', port=443):** Max retries exceeded with url: /v2/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5ca5c5a748>: Failed to establish a new connection: [Errno -2] Name or service not known',))"

if this message helps? I don't understand the registry information highlight above...

**Comment by MaGaoju** [comment]
@zhill  I think I found the cause of issue above. just print out the registry name, I think method: RegistryNameFromRepo(registry, repository) didn't return correct name ... 
time="2019-10-29T04:58:13Z" level=info msg="check registry host name : **registryName** : rnd-it/alpine"
time="2019-10-29T04:58:13Z" level=info msg="check registry host name : registry : harbor.corp.hpicloud.net"
time="2019-10-29T04:58:13Z" level=info msg="check registry host name : repository : rnd-it/alpine"
time="2019-10-29T04:58:13Z" level=info msg="check registry host name : registryAddUrl : https://anchore-api.corp.hpicloud.net/v1/registries"

**Comment by zhill** [comment]
Yes, that is definitely a bug. I'll have a fix in shortly.

**Comment by zhill** [comment]
If this is not resolved in your install, please re-open. I've addressed the 2 issues I found: url parsing and a url-encoding issue in the credential update codepath.

**Comment by Atharex** [comment]
I also got this error...

```
time="2020-06-23T06:54:16Z" level=debug msg="sending request" URL="http://anchore-anchore-engine-api.anchore.svc.cluster.local:8228/v1/registries" method=POST
time="2020-06-23T06:54:16Z" level=debug msg="api call duration" duration=693.580923ms
time="2020-06-23T06:54:16Z" level=debug msg="anchore API response" contentLength=572 contentType=application/json requestMethod=POST requestURL="http://anchore-anchore-engine-api.anchore.svc.cluster.local:8228/v1/registries?validate=true" status="406 NOT ACCEPTABLE" statusCode=406
time="2020-06-23T06:54:16Z" level=error msg="unexpected error response from anchore adding registry credential" receivedResponse="{\n  \"detail\": {\n    \"error_codes\": []\n  },\n  \"httpcode\": 406,\n  \"message\": \"cannot ping supplied registry with supplied credentials - exception: failed check to access registry (https://harbor.external.domain.com,robot$Anchore-588ceb4f-b51e-11ea-a2dc-06f6c9781c39) - exception: HTTPSConnectionPool(host='harbor.external.domain.com', port=443): Max retries exceeded with url: /v2/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7b09ce4978>: Failed to establish a new connection: [Errno -2] Name or service not known',))\"\n}\n" receivedStatusCode=406
time="2020-06-23T06:54:16Z" level=error msg="failed executing the scan request" err="failed to add valid credentials to anchore for registry"
time="2020-06-23T06:54:16Z" level=error msg="returning error response" code=500 message="failed to add valid credentials to anchore for registry"
```

The credentials and the request are correctly passed from Harbor to Anchore with the adapter, but the reverse lookup is not possible, since Anchore tries to add the Harbor registry from the external URL configured in the helm chart. 
**https://harbor.external.domain.com**

This will not work, because the external Harbor URL is not reachable from inside the anchore pod, unless you manually set up DNS entries. 
**(Failed to establish a new connection: [Errno -2] Name or service not known',)**

Is there a way to pass the reverse-lookup address of Harbor to Anchore? Something resolvable from within the Anchore pod (e.g. http://harbor-harbor-core.harbor.svc.cluster.local:80/)
